### ISSUE TITLE
关于闭包的数据结构

### ISSUE THREAD

**Issue by daleydeng** [RustyCab/LearnRustEasy#11]
![image](https://github.com/RustyCab/LearnRustEasy/assets/770506/165cca32-e49f-4d12-8f96-8b56cbd4bb9e)

闭包这块会捕捉y么，是不是x就够了

**Comment by DaviRain-Su** [comment]
y是闭包自身传递进来的参数，不是闭包捕获外面的内容。

**Comment by anonymousGiga** [comment]
对的，这个我晚点提个pr修改下，还得补充下知识点：对于不捕获环境变量的闭包是直接转换成函数指针

**Comment by anonymousGiga** [comment]
已经在 #13 中修改了
