### ISSUE TITLE
chapter_3_16_1 勘误

### ISSUE THREAD

**Issue by dvorakchen** [RustyCab/LearnRustEasy#7]
[3.16.1 智能指针介绍](https://github.com/RustyCab/LearnRustEasy/blob/main/src/chapter_3/chapter_3_16_1.md)

其中的表述：**智能指针是一类数据结构，其表现类似于指针，但是相对于指针来说，还拥有额外的元数据。最明显的是它们拥有一个引用计数。引用计数记录了智能指针总共有多少个所有者，并且当没有任何所有者时清除数据。**，有误

拥有一个引用计数的智能指针应该为 Rc, Arc，并不是所有智能指针，所以应当为：**智能指针是一类数据结构，其表现类似于指针，但是相对于指针来说，还拥有额外的元数据，并且当没有任何所有者时清除数据。**

另，**但是相对于指针来说，还拥有额外的元数据**，希望能够举例下，如：智能指针 `String`，拥有额外的元数据：capacity（容量）。以对区分指针和智能指针有具体的概念。

参考修改为：**智能指针是一类数据结构，其表现类似于指针，但是相对于指针来说，还拥有额外的元数据，并且当没有任何所有者时清除数据。如：智能指针 `String`，拥有额外的元数据：capacity（容量）**

**Comment by anonymousGiga** [comment]
已在 #10 中修改
